media:
  input: src/assets
  output: /src/assets
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: ogImage, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
      - name: heroImage
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
  - name: about
    label: About page
    type: file
    path: src/test.json
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
      - name: heroImage
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
      - name: listImages
        label: images gallery
        list: true
        type: image
        description: list of images
      - name: stringList
        label: list of strings
        list: true
        type: string
        description: this is a list of string
      - name: contact
        label: Contact information
        type: object
        list: true
        fields:
        - name: first_name
          label: First name
          type: string
        - name: last_name
          label: Last name
          type: string
        - name: email
          label: Email address
          type: string
        - name: phone
          label: Phone number
          type: string
